### ISSUE TITLE
Net Neutrality is harmful for the internet

### ISSUE THREAD

**Issue by jharraf** [fightforthefuture/battleforthenet-widget#143]
http://dailycaller.com/2017/12/08/roger-stone-time-for-real-net-neutrality/

**Comment by skipz36** [comment]
This is for **software issues**, not opinions.

**Comment by HarleyDawg** [comment]
Then don't put an "issues" link at the bottom of your net neutrality spam pop-up.

**Comment by rubbingalcoholic** [comment]
One of the main arguments in that piece boils down to "Facebook and Twitter censors conservatives, so Comcast should be able to as well trolololol" - that would be like saying AT&T should be able to block toll-free phone calls to long distance calling cards (remember when that was a thing?) since it's their free speech to block competing long distance providers and charge you whatever rates they want.

The Obviously the fact that Facebook, Twitter and YouTube are censoring conservatives is stupid. Nobody wants that except the most intellectually vacuous leftists.

If a Christian bakery doesn't want to bake a gay wedding cake, shouldn't that be their right? If a Muslim bakery doesn't want to bake a bacon cake, maybe that ought to be their right as well. If Facebook and Youtube don't want to let conservatives speak, then they're dumb as fuck, but that's probably also their right.

Net neutrality has nothing to do with that. It just treats the cable companies as _telecommunications companies_ and says they can't discriminate against certain types of web sites in favor of others. _It has nothing to do with what those web sites actually have on them._ So if the sites are retarded and don't let conservatives speak, then the free market can fix that with services like gab.ai, etc. that will knock Google and Facebook down a peg.

But saying your ISP should be able to block your access to the Internet because some web sites on the Internet are stupid is the intellectual equivalent of cutting off your nose to spite your face.

I'm closing your ticket but appreciate your opinion.
