### ISSUE TITLE
[Important] Make an offline zip package.

### ISSUE THREAD

**Issue by nonegit** [fightforthefuture/battleforthenet-widget#24]
If the user is using RequestPolicy(like me), your widget never trigger because the addon block 3rd party
connection. I want you to create ZIP package asap so I could implement on my website without 3rd party access.

**Comment by niccokunzmann** [comment]
Can you try if this works: (from [here](https://github.com/fightforthefuture/battleforthenet-widget))
![grafik](https://user-images.githubusercontent.com/564768/27772794-a05bb196-5f69-11e7-8b67-38c3c9cb9226.png)

**Comment by nonegit** [comment]
Did you read my comment before posting?

**Comment by niccokunzmann** [comment]
I read [this](https://github.com/fightforthefuture/battleforthenet-widget/issues/24#issue-240000129) before posting. I understood as much as "I want you to create ZIP package asap so I could implement on my website without 3rd party access." I am not sure what of the zip package I provided [here](https://github.com/fightforthefuture/battleforthenet-widget/issues/24#issuecomment-312510427) is satisfactory to you and what is leaving you in unfinished work. Would you like to elaborate on this?

**Comment by swise123tn** [comment]
I believe I know what he's talking about.  I am having an issue where Chrome will not display the window because it is being blocked...see screenshots.

![image](https://user-images.githubusercontent.com/29868144/27800441-01a841a6-5fdf-11e7-8fa0-7ca21d2de108.png)

![image](https://user-images.githubusercontent.com/29868144/27800449-0b51e16c-5fdf-11e7-97e0-edf9950936b7.png)

The normal user is not going to notice the icon and click Load unsafe scripts (at least they shouldn't).

Anyway around this issue?

**Comment by mikemorris** [comment]
@swise123tn Is this the same issue that was fixed in https://github.com/fightforthefuture/battleforthenet-widget/pull/23?

**Comment by swise123tn** [comment]
Well...I'm confused now because when I made my post it wasn't working...now it is.  Just ignore me...lol

**Comment by mikemorris** [comment]
Closing as possibly resolved in #23 and no clearly actionable next steps.
