### ISSUE TITLE
Issues on mobile

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#63]
Opened the tool in mobile:

iOSX > Google Inbox app > likely Safari wrapper

The tool is not mobile friendly. The form hangs off the screen horizontally. Each time you tap into a new input, the form jumps up and down and ends up somewhere else, so you need to scroll to find it. Sometimes when you scroll, it scrolls the "background" page behind the form, other times you can grab the form itself.

I still managed to submit the form but this seems pretty serious as most of your clicks are going to come in on mobile devices.

Great work with everything though, keep fighting the good fight! I'm with you

**Comment by b264** [comment]
`iOSX` ?

**Comment by jdc20181** [comment]
Appears to be all good in Safari, maybe it was fixed? 

I did not have that issue - I did two tests:

- Used the Chrome Dev Tools to simulate mobile view - because if it happens in mobile safari sometimes it occurs in chrome as well. 

- Tested in Safari on my Iphone 7+ Latest IOS 10.3.2 

I could not reproduce the issue, I had no issues filling out the form, or doing anything with the form.

**Comment by mikemorris** [comment]
I believe this was due to flexbox issues which have since been fixed.
