### ISSUE TITLE
For US IPs only? 

### ISSUE THREAD

**Issue by carlhoerberg** [fightforthefuture/battleforthenet-widget#83]
Can geo-ip be used to only show it for ppl in US (as they are the only ones able to do anything about it)?

**Comment by picapi** [comment]
I believe you could easily set up some preemptive javascript to poll a geolocation service, and then based upon the result you can choose to load the script or abort.

**Comment by holmesworcester** [comment]
we’ve done this in the past, but didn’t here because it’s completely legitimate for folks outside the US to comment to the FCC—foreign companies like T-Mobile certainly file in FCC proceedings, so individuals should be able to as well.

If you don’t have a US zipcode we won’t deliver your letter to Congress, and calls are only possible for US users (though there are other options that people outside the US can do)
